const githubResponse = """{
  "total_count": 5,
  "incomplete_results": false,
  "items": [
    {
      "login": "atsneves",
      "id": 1744187,
      "node_id": "MDQ6VXNlcjE3NDQxODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1744187?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/atsneves",
      "html_url": "https://github.com/atsneves",
      "followers_url": "https://api.github.com/users/atsneves/followers",
      "following_url": "https://api.github.com/users/atsneves/following{/other_user}",
      "gists_url": "https://api.github.com/users/atsneves/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/atsneves/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/atsneves/subscriptions",
      "organizations_url": "https://api.github.com/users/atsneves/orgs",
      "repos_url": "https://api.github.com/users/atsneves/repos",
      "events_url": "https://api.github.com/users/atsneves/events{/privacy}",
      "received_events_url": "https://api.github.com/users/atsneves/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "atsneves2017",
      "id": 29660593,
      "node_id": "MDQ6VXNlcjI5NjYwNTkz",
      "avatar_url": "https://avatars.githubusercontent.com/u/29660593?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/atsneves2017",
      "html_url": "https://github.com/atsneves2017",
      "followers_url": "https://api.github.com/users/atsneves2017/followers",
      "following_url": "https://api.github.com/users/atsneves2017/following{/other_user}",
      "gists_url": "https://api.github.com/users/atsneves2017/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/atsneves2017/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/atsneves2017/subscriptions",
      "organizations_url": "https://api.github.com/users/atsneves2017/orgs",
      "repos_url": "https://api.github.com/users/atsneves2017/repos",
      "events_url": "https://api.github.com/users/atsneves2017/events{/privacy}",
      "received_events_url": "https://api.github.com/users/atsneves2017/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "atsneves-zen",
      "id": 128617587,
      "node_id": "U_kgDOB6qMcw",
      "avatar_url": "https://avatars.githubusercontent.com/u/128617587?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/atsneves-zen",
      "html_url": "https://github.com/atsneves-zen",
      "followers_url": "https://api.github.com/users/atsneves-zen/followers",
      "following_url": "https://api.github.com/users/atsneves-zen/following{/other_user}",
      "gists_url": "https://api.github.com/users/atsneves-zen/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/atsneves-zen/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/atsneves-zen/subscriptions",
      "organizations_url": "https://api.github.com/users/atsneves-zen/orgs",
      "repos_url": "https://api.github.com/users/atsneves-zen/repos",
      "events_url": "https://api.github.com/users/atsneves-zen/events{/privacy}",
      "received_events_url": "https://api.github.com/users/atsneves-zen/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "atsnevesztech",
      "id": 105014709,
      "node_id": "U_kgDOBkJltQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/105014709?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/atsnevesztech",
      "html_url": "https://github.com/atsnevesztech",
      "followers_url": "https://api.github.com/users/atsnevesztech/followers",
      "following_url": "https://api.github.com/users/atsnevesztech/following{/other_user}",
      "gists_url": "https://api.github.com/users/atsnevesztech/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/atsnevesztech/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/atsnevesztech/subscriptions",
      "organizations_url": "https://api.github.com/users/atsnevesztech/orgs",
      "repos_url": "https://api.github.com/users/atsnevesztech/repos",
      "events_url": "https://api.github.com/users/atsnevesztech/events{/privacy}",
      "received_events_url": "https://api.github.com/users/atsnevesztech/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "peared-company",
      "id": 75390185,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjc1MzkwMTg1",
      "avatar_url": "https://avatars.githubusercontent.com/u/75390185?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/peared-company",
      "html_url": "https://github.com/peared-company",
      "followers_url": "https://api.github.com/users/peared-company/followers",
      "following_url": "https://api.github.com/users/peared-company/following{/other_user}",
      "gists_url": "https://api.github.com/users/peared-company/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/peared-company/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/peared-company/subscriptions",
      "organizations_url": "https://api.github.com/users/peared-company/orgs",
      "repos_url": "https://api.github.com/users/peared-company/repos",
      "events_url": "https://api.github.com/users/peared-company/events{/privacy}",
      "received_events_url": "https://api.github.com/users/peared-company/received_events",
      "type": "Organization",
      "site_admin": false,
      "score": 1.0
    }
  ]
}""";
